version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      DB_URL: ${DB_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - db
    networks:
      - my_network


  db:
    image: mariadb:11.0.3
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./sql-migrations:/docker-entrypoint-initdb.d
    networks:
      - my_network

networks:
  my_network: