version: '3'
services:
  app:
    build: .
    ports:
      - "4000:80"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: your_flask_app.api
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    networks:
      - my_network

networks:
  my_network: