version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      DB_URL: ${DB_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - db
    networks:
      - my_network


  db:
    container_name: db
    hostname: db
    image: mariadb:11.0.3
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./sql-migrations:/docker-entrypoint-initdb.d
    networks:
      - my_network

  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

networks:
  my_network: